[package]
name = "bininfo"
version = "0.1.0"
authors = ["thebarbershopper <cld251@gmail.com>"]
edition = "2021"

[dependencies]
binja-rs = { path = "../../../binja-rs" }
clap = { version = "4.4.4", features = ["derive"] }
