[package]
name = "cyclomatic_complexity"
version = "0.1.0"
authors = ["thebarbershopper <cld251@gmail.com>"]

[dependencies]
binja-rs = { path = "../../../binja-rs" }
clap = "*"
anyhow = "*"
rayon = "*"
